/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "LOGIC_BL.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{

	u8 rec[21] = {0x10, 0x04, 0xF0, 0x00, 0x80, 0xB4, 0x83
			   , 0xB0, 0x00, 0xAF, 0x78, 0x60, 0x39, 0x60
			   , 0x7B, 0x68, 0x07, 0x4A, 0xA2, 0xFB, 0xA4};
	Parser(rec);
	printf("Hello");
    /* Loop forever */
	for(;;);
}
