/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "DIO_interface.h"
#include "SYSTICK.h"
void APP(void);

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
    /* Loop forever */
	MRCC_voidInit();
	MRCC_enumSetPeripheralClock(APB2 , IOPBEN_ID, RCC_ENABLE );//////////////IOPAEN_ID not yet implemented
	DIO_voidSetPinDirection(PORTB, 5, GPIO_OUTPUT_2MHZ_PP);
	DIO_voidSetPinDirection(PORTB, 4, GPIO_OUTPUT_2MHZ_PP);
	SYSTICK_SetCallback (APP);
	SYSTICK_Init ();
	SYSTICK_SetTime_ms(1000, 8000000);
	SYSTICK_Start ();

	for(;;)
	{


		//DIO_voidTogglePin(PORTB, 4);
		//SYSTICK_SetTime_ms (1000, 1000000);

	}
}
void APP(void)
{
	DIO_voidTogglePin(PORTB, 4);
}
