/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "DIO_interface.h"
#include "rcc_int.h"
#include "NVIC.h"
#include "LCD.h"


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	u8 i = 0;
	MRCC_voidInit();
	MRCC_enumSetPeripheralClock(APB2 , IOPBEN_ID, RCC_ENABLE );
	DIO_voidSetPortnDirection(PORTB, GPIO_OUTPUT_2MHZ_PP);
	LCD_init();
	while(i >=5000)
	{
		i++;
	}
	i=0;
	LCD_write_command(0x0C); // display on, cursor off
	LCD_write_command(0x01);
	while(i >=500)
	{
		i++;
	}
	i=0;
	LCD_write_num(100);
	DNVIC_EnableIRQ(ADC1_2);
	DNVIC_EnableIRQ(USART1);
	DNVIC_EnableIRQ(WWDG); //18 adc 37 usart 0wdt
	DNVIC_SetPriorityGrouping(TWO_PREEMPTION_TWO_SUBGROUP);
	DNVIC_SetPriority(ADC1_2, 0x00, 0x00);
	DNVIC_SetPriority(USART1, 0x02, 0x03);
	DNVIC_SetPriority(WWDG, 0x01, 0x02);


    /* Loop forever */
	for(;;)
	{
		DIO_voidTogglePin(PORTB, 5);
		DNVIC_SetPendingIRQ (ADC1_2);
		DIO_voidTogglePin(PORTB, 5);
		DNVIC_SetPendingIRQ (USART1);
		DIO_voidTogglePin(PORTB, 5);
		DNVIC_SetPendingIRQ (WWDG);
	}
}
void  ADC1_2_IRQHandler(void)
{
	u8 i = 0;
	DIO_voidTogglePin(PORTB, 0);
	while(i >=5000)
	{
		i++;
	}
	i=0;
}
void USART1_IRQHandler(void)
{
	u8 i = 0;
	DIO_voidTogglePin(PORTB, 1);
	while(i >=5000)
	{
		i++;
	}
	i=0;
}
void WWDG_IRQHandler(void)
{
	u8 i = 0;
	DIO_voidTogglePin(PORTB, 2);
	while(i >=5000)
	{
		i++;
	}
	i=0;
}

